name: Run tests and lint pull requests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Fetch contributors
        run: bun run fetch-contributors
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build database
        run: bun run scripts/build-database.ts

      - name: Build
        run: bun run build
